<%@ Page Language="C#" AutoEventWireup="true" CodeFile="GridViewData.aspx.cs" Inherits="GridViewData" %>


    <form id="form1" runat="server">
<div id="divGridView">
    <asp:gridview id="GridView1" runat="server" enableviewstate="False" width="100%" BorderWidth="1"
        cellpadding="4" forecolor="#333333" gridlines="None" autogeneratecolumns="false"
        datakeyTrialNos="TransNo" autogeneratedeletebutton="false" EmptyDataText="No records found" >
            <HeaderStyle BackColor="#507CD1" HorizontalAlign="Left" Font-Bold="True" ForeColor="White" />
            <Columns>
                <asp:BoundField DataField="TransNo" HeaderText="TransNo" />
                <asp:TemplateField HeaderText="Edit">
                    <ItemTemplate>
                        <a href="javascript:void(0)" onclick="ShowEditBox(<%# Eval("TransNo") %>)" title="Edit">Edit</a>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="TrialNo">
                    <ItemTemplate>
                        <span id="PTrialNo<%# Eval("TransNo") %>"><%# Eval("TrialNo") %></span>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:BoundField HeaderText="Seq" DataField="Seq" />
                <asp:BoundField HeaderText="Machine" DataField="Machine" />
                <asp:BoundField HeaderText="Process" DataField="Process" />
                <asp:TemplateField HeaderText="Delete">
                    <ItemTemplate>
                        <span onclick="return confirm('Are you sure?')">
                            <a href="javascript:DeleteRecord(<%# Eval("TransNo") %>)" title="Delete"><font color="red">Delete?</font></a>
                        </span>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:gridview>
        <asp:Literal runat="server" ID="litPaging" EnableViewState="False" />
    <p>
        <asp:label id="lblMessage" runat="server" enableviewstate="false" />
    </p>
</div>
</form>

    <script language="javascript" type="text/javascript">
        // highlight the row when clicked
        $(document).ready(function () {
            $("#divGridView table tbody tr").mouseover(function () {
                $(this).addClass("highlightRow");
            }).mouseout(function () { $(this).removeClass('highlightRow'); })
        });

        // highlight row by clicking it
        $(document).ready(function () {
            $("#divGridView table tbody tr").click(function () {
                $(this).addClass("select");
            })
        });

        // double click delete rows
        $(document).ready(function () {
            $("#divGridView table tbody tr").dblclick(function () {
                // find the id first
                var v = confirm('Are you sure to delete?');
                if (v) {
                    var TransNo = $(this).find("td:first").text();
                    // remove the row from server side (the database)
                    DeleteRecord(TransNo);
                    // remove from the clien side
                    $(this).remove();
                }
            })
        });
</script>




